# Generated by Django 2.2.7 on 2019-12-04 14:06

import booker.enums
from django.db import migrations, models
import enumfields.fields
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('location_ref', models.CharField(blank=True, max_length=120, null=True)),
                ('formatted', models.CharField(blank=True, max_length=120, null=True)),
                ('lat', models.CharField(blank=True, max_length=20, null=True)),
                ('lng', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icabbi_id', models.CharField(blank=True, max_length=120, null=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pickup', models.CharField(max_length=120)),
                ('pickup_ref', models.CharField(max_length=120)),
                ('pickup_lat', models.CharField(max_length=20)),
                ('pickup_lng', models.CharField(max_length=20)),
                ('pickup_date', models.DateTimeField(blank=True, null=True)),
                ('dropoff', models.CharField(max_length=120)),
                ('dropoff_ref', models.CharField(max_length=120)),
                ('dropoff_lat', models.CharField(max_length=20)),
                ('dropoff_lng', models.CharField(max_length=20)),
                ('via1_lat', models.CharField(blank=True, max_length=20, null=True)),
                ('via1_lng', models.CharField(blank=True, max_length=20, null=True)),
                ('via1', models.CharField(blank=True, max_length=20, null=True)),
                ('via1_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('via2_lat', models.CharField(blank=True, max_length=20, null=True)),
                ('via2_lng', models.CharField(blank=True, max_length=20, null=True)),
                ('via2', models.CharField(blank=True, max_length=20, null=True)),
                ('via2_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('via3_lat', models.CharField(blank=True, max_length=20, null=True)),
                ('via3_lng', models.CharField(blank=True, max_length=20, null=True)),
                ('via3', models.CharField(blank=True, max_length=20, null=True)),
                ('via3_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('payment', enumfields.fields.EnumField(default='CASH', enum=booker.enums.PaymentType, max_length=120)),
                ('vehicle_title', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_group', models.CharField(blank=True, max_length=20, null=True)),
                ('status', enumfields.fields.EnumField(default='PENDING', enum=booker.enums.BookingStatus, max_length=120)),
                ('icabbi_status', enumfields.fields.EnumField(default='NEW', enum=booker.enums.IcabbiStatus, max_length=120)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('pickup_extra', models.CharField(blank=True, max_length=120, null=True)),
                ('icabbi_response', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pickup', models.CharField(max_length=120)),
                ('pickup_ref', models.CharField(max_length=120)),
                ('pickup_lat', models.CharField(max_length=20)),
                ('pickup_lng', models.CharField(max_length=20)),
                ('dropoff', models.CharField(max_length=20)),
                ('dropoff_ref', models.CharField(max_length=120)),
                ('dropoff_lat', models.CharField(max_length=20)),
                ('dropoff_lng', models.CharField(max_length=20)),
                ('via1_ref', models.CharField(blank=True, max_length=20, null=True)),
                ('via1_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('via2_ref', models.CharField(blank=True, max_length=20, null=True)),
                ('via2_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('via3_ref', models.CharField(blank=True, max_length=20, null=True)),
                ('via3_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estimated_time', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
