# Generated by Django 2.2.7 on 2019-12-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='via1',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='via1_lat',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='via1_lng',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='via1_price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='via2',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='via2_lat',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='via2_lng',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='via2_price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='via3',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='via3_lat',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='via3_lng',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='via3_price',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='via1_postcode',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='via1_ref',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='via2_postcode',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='via2_ref',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='via3_postcode',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='via3_ref',
        ),
        migrations.AlterField(
            model_name='booking',
            name='dropoff',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='booking',
            name='dropoff_lat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='dropoff_lng',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_lat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_lng',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='dropoff',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='pickup',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
