from enumfields import Enum


class BookingStatus(Enum):
    PENDING = "PENDING"
    SUBMITTED = "SUBMITTED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class IcabbiStatus(Enum):
    NEW = 'NEW'
    ASSIGN = 'ASSIGN'
    BACK_TO_BASE = 'BACKTOBASE'
    PAUSED = 'PAUSED'
    ARRIVED = 'ARRIVED'
    NO_SHOW = 'NOSHOW'
    EN_ROUTE = 'ENROUTE'
    FOLLOW_ON = 'FOLLOWON'
    WAIT = 'WAIT'
    TRANSFERRED = 'TRANSFERRED'
    MADE_CONTACT = 'MADECONTACT'
    DROPPING_OFF = 'DROPPINGOFF'
    CUSTOMER_CANCELLED = 'CUSTOMER_CANCELLED'
    DRIVER_CANCELLED = 'DRIVER_CANCELLED'
    DISPATCH_CANCELLED = 'DISPATCH_CANCELLED'
    COMPLETED = 'COMPLETED'


class PaymentType(Enum):
    CASH = 'CASH'
    CARD = 'CARD'
